name: Download and Create Esbuild Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'שם התג והריליס (למשל v0.28.1)'
        required: true
        default: 'v0.28.1'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        run: |
          curl -L -o win32-x64-0.28.1.tgz "https://registry.npmjs.org/@esbuild/win32-x64/-/win32-x64-0.28.1.tgz"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: Release ${{ github.event.inputs.tag_name }}
          files: win32-x64-0.28.1.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
